/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipo;

import com.sun.org.apache.xerces.internal.impl.dv.DVFactoryException;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectOutputStream;
import java.io.Writer;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.ListIterator;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Adrián
 */
public class Grafico extends javax.swing.JFrame {

    /**
     * Creates new form Grafico
     */
    public static ListIterator ite;
    public static ArrayList<Coche> c;

    public Grafico() throws FileNotFoundException, IOException {
        initComponents();

        c = new ArrayList<>();
        BufferedReader br = new BufferedReader(new FileReader("src/ipo/Coches"));
        for (String linea = br.readLine(); linea != null; linea = br.readLine()) {
            String[] divLinea = linea.split(",");
            Coche coche = new Coche(divLinea[0], Integer.parseInt(divLinea[1]), divLinea[2], Float.parseFloat(divLinea[3]));
            c.add(coche);
        }
        ite = c.listIterator();
        //getIdiomas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenuItem1 = new javax.swing.JMenuItem();
        labelmarca = new javax.swing.JLabel();
        ano = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        modelo = new javax.swing.JTextField();
        labelaño = new javax.swing.JLabel();
        labelmodelo = new javax.swing.JLabel();
        labelprecio = new javax.swing.JLabel();
        anadir = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        save = new javax.swing.JMenuItem();
        menuIdioma = new javax.swing.JMenu();
        bandera = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(744, 428));
        setPreferredSize(new java.awt.Dimension(744, 428));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelmarca.setLabelFor(ano);
        labelmarca.setText("Marca");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(labelmarca, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 1);
        getContentPane().add(ano, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(marca, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 10);
        getContentPane().add(precio, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 10);
        getContentPane().add(modelo, gridBagConstraints);

        labelaño.setText("Año");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 9, 2, 17);
        getContentPane().add(labelaño, gridBagConstraints);

        labelmodelo.setText("Modelo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 11, 2, 19);
        getContentPane().add(labelmodelo, gridBagConstraints);

        labelprecio.setText("Precio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 10);
        getContentPane().add(labelprecio, gridBagConstraints);

        anadir.setText("Añadir");
        anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 10);
        getContentPane().add(anadir, gridBagConstraints);

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 10);
        getContentPane().add(eliminar, gridBagConstraints);

        siguiente.setText("Siguiente");
        siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siguienteMouseClicked(evt);
            }
        });
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 10);
        getContentPane().add(siguiente, gridBagConstraints);

        anterior.setText("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(anterior, gridBagConstraints);

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 10);
        getContentPane().add(modificar, gridBagConstraints);

        archivo.setLabel("Archivo");

        save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        save.setText("Guardar");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        archivo.add(save);

        jMenuBar1.add(archivo);

        menuIdioma.setLabel("Idioma");
        menuIdioma.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuIdiomaMenuSelected(evt);
            }
        });
        menuIdioma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuIdiomaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuIdioma);

        bandera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipo/esp.PNG"))); // NOI18N
        jMenuBar1.add(bandera);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siguienteActionPerformed

    private void siguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siguienteMouseClicked
        siguiente();
    }//GEN-LAST:event_siguienteMouseClicked

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
       modificar();
    }//GEN-LAST:event_modificarActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        anterior();
    }//GEN-LAST:event_anteriorActionPerformed

    private void anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirActionPerformed
        anadir();        // TODO add your handling code here:
    }//GEN-LAST:event_anadirActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_eliminarActionPerformed

    private void menuIdiomaMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuIdiomaMenuSelected

    }//GEN-LAST:event_menuIdiomaMenuSelected

    private void menuIdiomaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuIdiomaMouseClicked
        try {
            new SelectorIdiomas(this, rootPaneCheckingEnabled).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Grafico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuIdiomaMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
            save();
        } catch (IOException ex) {
            Logger.getLogger(Grafico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Grafico().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Grafico.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadir;
    private javax.swing.JTextField ano;
    private javax.swing.JButton anterior;
    private javax.swing.JMenu archivo;
    private javax.swing.JMenu bandera;
    private javax.swing.JButton eliminar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel labelaño;
    private javax.swing.JLabel labelmarca;
    private javax.swing.JLabel labelmodelo;
    private javax.swing.JLabel labelprecio;
    private javax.swing.JTextField marca;
    private javax.swing.JMenu menuIdioma;
    private javax.swing.JTextField modelo;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField precio;
    private javax.swing.JMenuItem save;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables
    public void siguiente() {
        if (ite.hasNext()) {
//            ite.remove();
            mostrarCoche(ite.nextIndex());

            anterior.setEnabled(true);
        } else {
            siguiente.setEnabled(false);
            ite.previous();
        }

        ite.next();
    }

    public void anterior() {
        if (ite.hasPrevious()) {

            mostrarCoche(ite.previousIndex());

            siguiente.setEnabled(true);

        } else {
            anterior.setEnabled(false);
            ite.next();

        }

        ite.previous();
    }

    public void mostrarCoche(int pos) {
        System.out.println(c.get(pos).getMarca() + c.get(pos).getAnio() + c.get(pos).getModelo() + c.get(pos).getPrecio());
        marca.setText(c.get(pos).getMarca());
        ano.setText("" + c.get(pos).getAnio());
        modelo.setText(c.get(pos).getModelo());
        precio.setText("" + c.get(pos).getPrecio());
    }

    public void leerFichero(String idioma) throws FileNotFoundException, IOException {
        cambiarIdioma(new BufferedReader(new FileReader("src/ipo/Coches_" + idioma + ".txt")).readLine());
    }

    public void cambiarIdioma(String linea) throws IOException {
        System.out.println(linea);
        String[] divLinea = linea.split(",");
        menuIdioma.setText(divLinea[0]);
        labelprecio.setText(divLinea[1]);
       
        labelmodelo.setText(divLinea[3]);
        save.setText(divLinea[4]);
        labelaño.setText(divLinea[5]);
        archivo.setText(divLinea[6]);
        modificar.setText(divLinea[7]);
        anterior.setText(divLinea[8]);
        labelmarca.setText(divLinea[9]);
        siguiente.setText(divLinea[10]);
        eliminar.setText(divLinea[11]);
        anadir.setText(divLinea[12]);
        bandera.setIcon((Icon) new ImageIcon("src/ipo/" + divLinea[13]));
    }

    public void anadir() {
        System.out.println(marca.getText() + ano.getText());
        Coche c1 = new Coche(marca.getText(), Integer.parseInt(ano.getText()), modelo.getText(), Float.parseFloat(precio.getText()));
        c.add(c1);
        ite = c.listIterator();
    }

    public void eliminar() {
        int r = ite.nextIndex();
        r = r - 1;
        c.remove(r);
        marca.setText("");
        ano.setText("");
        precio.setText("");
        modelo.setText("");
        ite = c.listIterator();
        for (int i = 0; i < r; i++) {
            ite.next();
        }

    }
    public void modificar(){
        int r = ite.nextIndex();
        r = r - 1;
        c.get(r).setModelo(modelo.getText());
        c.get(r).setMarca(marca.getText());
        c.get(r).setPrecio(Float.parseFloat(precio.getText()));
        c.get(r).setAnio(Integer.parseInt(ano.getText()));
    }
    public void save() throws IOException{
        FileWriter fw = new FileWriter ("src/ipo/coches");
        Writer output = new BufferedWriter (fw);
        int sz = c.size();
        for (int i=0; i< sz; i++){
            output.write (c.get(i).getMarca() +","+ c.get(i).getAnio() +","+ c.get(i).getModelo() +","+c.get(i).getPrecio()+"\n");
        }
        output.close();
    }
    
   
}
